### ISSUE TITLE
HeatMap is invalid

### ISSUE THREAD

**Issue by willayy** [willayy/DAT257-Agile#52] opened 2024-05-10 14:45 UTC
The heatmap does not work (it doesnt display the different municipalities with different colors) until you select län and then kommun again.

The heat map also isn't updated when you change crime type, for example if you press "fjällräddning" and then "bråk" the "heat" from fjällräddning is still there.

**Comment by 0-Gixty-0** [comment] 2024-05-13 10:06
I am unable to reproduce the bug described in the issue. Just now I created a new branch and tested the bug which does not appear for me. I am wondering if the bug appeared before everything was pulled into the workspace... See attached images:
![image](https://github.com/willayy/DAT257-Agile/assets/107652880/adb07bd7-e0d0-4d5a-b928-226b2c35f637)
![image](https://github.com/willayy/DAT257-Agile/assets/107652880/122000ec-8f33-4ff6-829c-6b5dd3426cc7)

**Comment by 0-Gixty-0** [comment] 2024-05-15 13:04
Closing now based on previous comment and that the error was never reproduced when I worked on #55

**Closed by 0-Gixty-0** 2024-05-15 13:04 UTC
Labels: invalid
